// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logic/alarm_data.proto

package com.ideal.logic;

public final class alarm_data {
  private alarm_data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface read_alarm_reqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes uid = 1;
    boolean hasUid();
    com.google.protobuf.ByteString getUid();
    
    // optional uint64 start_time = 2;
    boolean hasStartTime();
    long getStartTime();
    
    // optional uint64 end_time = 3;
    boolean hasEndTime();
    long getEndTime();
    
    // optional string sessionid = 4;
    boolean hasSessionid();
    String getSessionid();
  }
  public static final class read_alarm_req extends
      com.google.protobuf.GeneratedMessage
      implements read_alarm_reqOrBuilder {
    // Use read_alarm_req.newBuilder() to construct.
    private read_alarm_req(Builder builder) {
      super(builder);
    }
    private read_alarm_req(boolean noInit) {}
    
    private static final read_alarm_req defaultInstance;
    public static read_alarm_req getDefaultInstance() {
      return defaultInstance;
    }
    
    public read_alarm_req getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alarm_data.internal_static_com_ideal_logic_read_alarm_req_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alarm_data.internal_static_com_ideal_logic_read_alarm_req_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uid_;
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getUid() {
      return uid_;
    }
    
    // optional uint64 start_time = 2;
    public static final int START_TIME_FIELD_NUMBER = 2;
    private long startTime_;
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getStartTime() {
      return startTime_;
    }
    
    // optional uint64 end_time = 3;
    public static final int END_TIME_FIELD_NUMBER = 3;
    private long endTime_;
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getEndTime() {
      return endTime_;
    }
    
    // optional string sessionid = 4;
    public static final int SESSIONID_FIELD_NUMBER = 4;
    private Object sessionid_;
    public boolean hasSessionid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getSessionid() {
      Object ref = sessionid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionidBytes() {
      Object ref = sessionid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uid_ = com.google.protobuf.ByteString.EMPTY;
      startTime_ = 0L;
      endTime_ = 0L;
      sessionid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSessionidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, startTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, endTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSessionidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static read_alarm_req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static read_alarm_req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static read_alarm_req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static read_alarm_req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static read_alarm_req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static read_alarm_req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static read_alarm_req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static read_alarm_req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static read_alarm_req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static read_alarm_req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(read_alarm_req prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements read_alarm_reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alarm_data.internal_static_com_ideal_logic_read_alarm_req_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alarm_data.internal_static_com_ideal_logic_read_alarm_req_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.alarm_data.read_alarm_req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return read_alarm_req.getDescriptor();
      }
      
      public read_alarm_req getDefaultInstanceForType() {
        return read_alarm_req.getDefaultInstance();
      }
      
      public read_alarm_req build() {
        read_alarm_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private read_alarm_req buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        read_alarm_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public read_alarm_req buildPartial() {
        read_alarm_req result = new read_alarm_req(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessionid_ = sessionid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof read_alarm_req) {
          return mergeFrom((read_alarm_req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(read_alarm_req other) {
        if (other == read_alarm_req.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasSessionid()) {
          setSessionid(other.getSessionid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uid_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startTime_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endTime_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              sessionid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes uid = 1;
      private com.google.protobuf.ByteString uid_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getUid() {
        return uid_;
      }
      public Builder setUid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      
      // optional uint64 start_time = 2;
      private long startTime_ ;
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getStartTime() {
        return startTime_;
      }
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000002;
        startTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 end_time = 3;
      private long endTime_ ;
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getEndTime() {
        return endTime_;
      }
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000004;
        endTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string sessionid = 4;
      private Object sessionid_ = "";
      public boolean hasSessionid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getSessionid() {
        Object ref = sessionid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sessionid_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionid_ = getDefaultInstance().getSessionid();
        onChanged();
        return this;
      }
      void setSessionid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        sessionid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.read_alarm_req)
    }
    
    static {
      defaultInstance = new read_alarm_req(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.read_alarm_req)
  }
  
  public interface alarm_data_infoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 start_time = 1;
    boolean hasStartTime();
    long getStartTime();
    
    // required int32 elapse_time = 2;
    boolean hasElapseTime();
    int getElapseTime();
    
    // required int32 alarm_code = 3;
    boolean hasAlarmCode();
    int getAlarmCode();
    
    // required bytes alarm_code_array = 4;
    boolean hasAlarmCodeArray();
    com.google.protobuf.ByteString getAlarmCodeArray();
  }
  public static final class alarm_data_info extends
      com.google.protobuf.GeneratedMessage
      implements alarm_data_infoOrBuilder {
    // Use alarm_data_info.newBuilder() to construct.
    private alarm_data_info(Builder builder) {
      super(builder);
    }
    private alarm_data_info(boolean noInit) {}
    
    private static final alarm_data_info defaultInstance;
    public static alarm_data_info getDefaultInstance() {
      return defaultInstance;
    }
    
    public alarm_data_info getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alarm_data.internal_static_com_ideal_logic_alarm_data_info_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alarm_data.internal_static_com_ideal_logic_alarm_data_info_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 start_time = 1;
    public static final int START_TIME_FIELD_NUMBER = 1;
    private long startTime_;
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getStartTime() {
      return startTime_;
    }
    
    // required int32 elapse_time = 2;
    public static final int ELAPSE_TIME_FIELD_NUMBER = 2;
    private int elapseTime_;
    public boolean hasElapseTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getElapseTime() {
      return elapseTime_;
    }
    
    // required int32 alarm_code = 3;
    public static final int ALARM_CODE_FIELD_NUMBER = 3;
    private int alarmCode_;
    public boolean hasAlarmCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAlarmCode() {
      return alarmCode_;
    }
    
    // required bytes alarm_code_array = 4;
    public static final int ALARM_CODE_ARRAY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString alarmCodeArray_;
    public boolean hasAlarmCodeArray() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getAlarmCodeArray() {
      return alarmCodeArray_;
    }
    
    private void initFields() {
      startTime_ = 0L;
      elapseTime_ = 0;
      alarmCode_ = 0;
      alarmCodeArray_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStartTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElapseTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmCodeArray()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, elapseTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, alarmCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, alarmCodeArray_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, elapseTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, alarmCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, alarmCodeArray_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static alarm_data_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static alarm_data_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static alarm_data_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static alarm_data_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static alarm_data_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static alarm_data_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static alarm_data_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static alarm_data_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static alarm_data_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static alarm_data_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(alarm_data_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements alarm_data_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alarm_data.internal_static_com_ideal_logic_alarm_data_info_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alarm_data.internal_static_com_ideal_logic_alarm_data_info_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.alarm_data.alarm_data_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        startTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        elapseTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        alarmCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        alarmCodeArray_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return alarm_data_info.getDescriptor();
      }
      
      public alarm_data_info getDefaultInstanceForType() {
        return alarm_data_info.getDefaultInstance();
      }
      
      public alarm_data_info build() {
        alarm_data_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private alarm_data_info buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        alarm_data_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public alarm_data_info buildPartial() {
        alarm_data_info result = new alarm_data_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startTime_ = startTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.elapseTime_ = elapseTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.alarmCode_ = alarmCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.alarmCodeArray_ = alarmCodeArray_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof alarm_data_info) {
          return mergeFrom((alarm_data_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(alarm_data_info other) {
        if (other == alarm_data_info.getDefaultInstance()) return this;
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasElapseTime()) {
          setElapseTime(other.getElapseTime());
        }
        if (other.hasAlarmCode()) {
          setAlarmCode(other.getAlarmCode());
        }
        if (other.hasAlarmCodeArray()) {
          setAlarmCodeArray(other.getAlarmCodeArray());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStartTime()) {
          
          return false;
        }
        if (!hasElapseTime()) {
          
          return false;
        }
        if (!hasAlarmCode()) {
          
          return false;
        }
        if (!hasAlarmCodeArray()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              startTime_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              elapseTime_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              alarmCode_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              alarmCodeArray_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 start_time = 1;
      private long startTime_ ;
      public boolean hasStartTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getStartTime() {
        return startTime_;
      }
      public Builder setStartTime(long value) {
        bitField0_ |= 0x00000001;
        startTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTime_ = 0L;
        onChanged();
        return this;
      }
      
      // required int32 elapse_time = 2;
      private int elapseTime_ ;
      public boolean hasElapseTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getElapseTime() {
        return elapseTime_;
      }
      public Builder setElapseTime(int value) {
        bitField0_ |= 0x00000002;
        elapseTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearElapseTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        elapseTime_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 alarm_code = 3;
      private int alarmCode_ ;
      public boolean hasAlarmCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAlarmCode() {
        return alarmCode_;
      }
      public Builder setAlarmCode(int value) {
        bitField0_ |= 0x00000004;
        alarmCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlarmCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        alarmCode_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes alarm_code_array = 4;
      private com.google.protobuf.ByteString alarmCodeArray_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAlarmCodeArray() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getAlarmCodeArray() {
        return alarmCodeArray_;
      }
      public Builder setAlarmCodeArray(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        alarmCodeArray_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlarmCodeArray() {
        bitField0_ = (bitField0_ & ~0x00000008);
        alarmCodeArray_ = getDefaultInstance().getAlarmCodeArray();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.alarm_data_info)
    }
    
    static {
      defaultInstance = new alarm_data_info(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.alarm_data_info)
  }
  
  public interface read_alarm_data_responseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes uid = 1;
    boolean hasUid();
    com.google.protobuf.ByteString getUid();
    
    // repeated .com.ideal.logic.alarm_data_info info = 2;
    java.util.List<alarm_data_info>
        getInfoList();
    alarm_data_info getInfo(int index);
    int getInfoCount();
    java.util.List<? extends alarm_data_infoOrBuilder>
        getInfoOrBuilderList();
    alarm_data_infoOrBuilder getInfoOrBuilder(
            int index);
    
    // optional string sessionid = 3;
    boolean hasSessionid();
    String getSessionid();
  }
  public static final class read_alarm_data_response extends
      com.google.protobuf.GeneratedMessage
      implements read_alarm_data_responseOrBuilder {
    // Use read_alarm_data_response.newBuilder() to construct.
    private read_alarm_data_response(Builder builder) {
      super(builder);
    }
    private read_alarm_data_response(boolean noInit) {}
    
    private static final read_alarm_data_response defaultInstance;
    public static read_alarm_data_response getDefaultInstance() {
      return defaultInstance;
    }
    
    public read_alarm_data_response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alarm_data.internal_static_com_ideal_logic_read_alarm_data_response_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alarm_data.internal_static_com_ideal_logic_read_alarm_data_response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString uid_;
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getUid() {
      return uid_;
    }
    
    // repeated .com.ideal.logic.alarm_data_info info = 2;
    public static final int INFO_FIELD_NUMBER = 2;
    private java.util.List<alarm_data_info> info_;
    public java.util.List<alarm_data_info> getInfoList() {
      return info_;
    }
    public java.util.List<? extends alarm_data_infoOrBuilder>
        getInfoOrBuilderList() {
      return info_;
    }
    public int getInfoCount() {
      return info_.size();
    }
    public alarm_data_info getInfo(int index) {
      return info_.get(index);
    }
    public alarm_data_infoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }
    
    // optional string sessionid = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private Object sessionid_;
    public boolean hasSessionid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSessionid() {
      Object ref = sessionid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionidBytes() {
      Object ref = sessionid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uid_ = com.google.protobuf.ByteString.EMPTY;
      info_ = java.util.Collections.emptyList();
      sessionid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInfoCount(); i++) {
        if (!getInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, uid_);
      }
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(2, info_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getSessionidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, uid_);
      }
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, info_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static read_alarm_data_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static read_alarm_data_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static read_alarm_data_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static read_alarm_data_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static read_alarm_data_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static read_alarm_data_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static read_alarm_data_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static read_alarm_data_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static read_alarm_data_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static read_alarm_data_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(read_alarm_data_response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements read_alarm_data_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return alarm_data.internal_static_com_ideal_logic_read_alarm_data_response_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return alarm_data.internal_static_com_ideal_logic_read_alarm_data_response_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.alarm_data.read_alarm_data_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          infoBuilder_.clear();
        }
        sessionid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return read_alarm_data_response.getDescriptor();
      }
      
      public read_alarm_data_response getDefaultInstanceForType() {
        return read_alarm_data_response.getDefaultInstance();
      }
      
      public read_alarm_data_response build() {
        read_alarm_data_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private read_alarm_data_response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        read_alarm_data_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public read_alarm_data_response buildPartial() {
        read_alarm_data_response result = new read_alarm_data_response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessionid_ = sessionid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof read_alarm_data_response) {
          return mergeFrom((read_alarm_data_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(read_alarm_data_response other) {
        if (other == read_alarm_data_response.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000002);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        if (other.hasSessionid()) {
          setSessionid(other.getSessionid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        for (int i = 0; i < getInfoCount(); i++) {
          if (!getInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uid_ = input.readBytes();
              break;
            }
            case 18: {
              alarm_data_info.Builder subBuilder = alarm_data_info.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addInfo(subBuilder.buildPartial());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes uid = 1;
      private com.google.protobuf.ByteString uid_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getUid() {
        return uid_;
      }
      public Builder setUid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      
      // repeated .com.ideal.logic.alarm_data_info info = 2;
      private java.util.List<alarm_data_info> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          info_ = new java.util.ArrayList<alarm_data_info>(info_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          alarm_data_info, alarm_data_info.Builder, alarm_data_infoOrBuilder> infoBuilder_;
      
      public java.util.List<alarm_data_info> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      public alarm_data_info getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      public Builder setInfo(
          int index, alarm_data_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setInfo(
          int index, alarm_data_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addInfo(alarm_data_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addInfo(
          int index, alarm_data_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addInfo(
          alarm_data_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addInfo(
          int index, alarm_data_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllInfo(
          Iterable<? extends alarm_data_info> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          super.addAll(values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      public alarm_data_info.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      public alarm_data_infoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends alarm_data_infoOrBuilder>
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      public alarm_data_info.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            alarm_data_info.getDefaultInstance());
      }
      public alarm_data_info.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, alarm_data_info.getDefaultInstance());
      }
      public java.util.List<alarm_data_info.Builder>
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          alarm_data_info, alarm_data_info.Builder, alarm_data_infoOrBuilder>
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              alarm_data_info, alarm_data_info.Builder, alarm_data_infoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      
      // optional string sessionid = 3;
      private Object sessionid_ = "";
      public boolean hasSessionid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getSessionid() {
        Object ref = sessionid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionid_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionid_ = getDefaultInstance().getSessionid();
        onChanged();
        return this;
      }
      void setSessionid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        sessionid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.read_alarm_data_response)
    }
    
    static {
      defaultInstance = new read_alarm_data_response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.read_alarm_data_response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_read_alarm_req_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_read_alarm_req_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_alarm_data_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_alarm_data_info_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_read_alarm_data_response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_read_alarm_data_response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026logic/alarm_data.proto\022\017com.ideal.logi" +
      "c\"V\n\016read_alarm_req\022\013\n\003uid\030\001 \002(\014\022\022\n\nstar" +
      "t_time\030\002 \001(\004\022\020\n\010end_time\030\003 \001(\004\022\021\n\tsessio" +
      "nid\030\004 \001(\t\"h\n\017alarm_data_info\022\022\n\nstart_ti" +
      "me\030\001 \002(\004\022\023\n\013elapse_time\030\002 \002(\005\022\022\n\nalarm_c" +
      "ode\030\003 \002(\005\022\030\n\020alarm_code_array\030\004 \002(\014\"j\n\030r" +
      "ead_alarm_data_response\022\013\n\003uid\030\001 \002(\014\022.\n\004" +
      "info\030\002 \003(\0132 .com.ideal.logic.alarm_data_" +
      "info\022\021\n\tsessionid\030\003 \001(\tB#\n\017com.ideal.log" +
      "icB\nalarm_data\200\001\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ideal_logic_read_alarm_req_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ideal_logic_read_alarm_req_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_read_alarm_req_descriptor,
              new String[] { "Uid", "StartTime", "EndTime", "Sessionid", },
              read_alarm_req.class,
              read_alarm_req.Builder.class);
          internal_static_com_ideal_logic_alarm_data_info_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ideal_logic_alarm_data_info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_alarm_data_info_descriptor,
              new String[] { "StartTime", "ElapseTime", "AlarmCode", "AlarmCodeArray", },
              alarm_data_info.class,
              alarm_data_info.Builder.class);
          internal_static_com_ideal_logic_read_alarm_data_response_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_ideal_logic_read_alarm_data_response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_read_alarm_data_response_descriptor,
              new String[] { "Uid", "Info", "Sessionid", },
              read_alarm_data_response.class,
              read_alarm_data_response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
