// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logic/online_info.proto

package com.ideal.logic;

public final class online_info {
  private online_info() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface update_online_status_requestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string user_name = 1;
    boolean hasUserName();
    String getUserName();
  }
  public static final class update_online_status_request extends
      com.google.protobuf.GeneratedMessage
      implements update_online_status_requestOrBuilder {
    // Use update_online_status_request.newBuilder() to construct.
    private update_online_status_request(Builder builder) {
      super(builder);
    }
    private update_online_status_request(boolean noInit) {}
    
    private static final update_online_status_request defaultInstance;
    public static update_online_status_request getDefaultInstance() {
      return defaultInstance;
    }
    
    public update_online_status_request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return online_info.internal_static_com_ideal_logic_update_online_status_request_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return online_info.internal_static_com_ideal_logic_update_online_status_request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string user_name = 1;
    public static final int USER_NAME_FIELD_NUMBER = 1;
    private Object userName_;
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      userName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static update_online_status_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static update_online_status_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static update_online_status_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static update_online_status_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static update_online_status_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static update_online_status_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static update_online_status_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static update_online_status_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static update_online_status_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static update_online_status_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(update_online_status_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements update_online_status_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return online_info.internal_static_com_ideal_logic_update_online_status_request_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return online_info.internal_static_com_ideal_logic_update_online_status_request_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.online_info.update_online_status_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return update_online_status_request.getDescriptor();
      }
      
      public update_online_status_request getDefaultInstanceForType() {
        return update_online_status_request.getDefaultInstance();
      }
      
      public update_online_status_request build() {
        update_online_status_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private update_online_status_request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        update_online_status_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public update_online_status_request buildPartial() {
        update_online_status_request result = new update_online_status_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof update_online_status_request) {
          return mergeFrom((update_online_status_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(update_online_status_request other) {
        if (other == update_online_status_request.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          setUserName(other.getUserName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string user_name = 1;
      private Object userName_ = "";
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      void setUserName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.update_online_status_request)
    }
    
    static {
      defaultInstance = new update_online_status_request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.update_online_status_request)
  }
  
  public interface single_online_infoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string uid = 1;
    boolean hasUid();
    String getUid();
    
    // required bytes mod_address = 2;
    boolean hasModAddress();
    com.google.protobuf.ByteString getModAddress();
    
    // required bytes data_address = 3;
    boolean hasDataAddress();
    com.google.protobuf.ByteString getDataAddress();
    
    // required string file_name = 4;
    boolean hasFileName();
    String getFileName();
    
    // required int32 alarm_code = 5;
    boolean hasAlarmCode();
    int getAlarmCode();
    
    // required float longitude = 6;
    boolean hasLongitude();
    float getLongitude();
    
    // required float latitude = 7;
    boolean hasLatitude();
    float getLatitude();
    
    // required string device_name = 8;
    boolean hasDeviceName();
    String getDeviceName();
    
    // required double longitude_double = 9;
    boolean hasLongitudeDouble();
    double getLongitudeDouble();
    
    // required double latitude_double = 10;
    boolean hasLatitudeDouble();
    double getLatitudeDouble();
    
    // required bytes alarm_code_array = 11;
    boolean hasAlarmCodeArray();
    com.google.protobuf.ByteString getAlarmCodeArray();
  }
  public static final class single_online_info extends
      com.google.protobuf.GeneratedMessage
      implements single_online_infoOrBuilder {
    // Use single_online_info.newBuilder() to construct.
    private single_online_info(Builder builder) {
      super(builder);
    }
    private single_online_info(boolean noInit) {}
    
    private static final single_online_info defaultInstance;
    public static single_online_info getDefaultInstance() {
      return defaultInstance;
    }
    
    public single_online_info getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return online_info.internal_static_com_ideal_logic_single_online_info_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return online_info.internal_static_com_ideal_logic_single_online_info_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private Object uid_;
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUid() {
      Object ref = uid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUidBytes() {
      Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes mod_address = 2;
    public static final int MOD_ADDRESS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString modAddress_;
    public boolean hasModAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getModAddress() {
      return modAddress_;
    }
    
    // required bytes data_address = 3;
    public static final int DATA_ADDRESS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString dataAddress_;
    public boolean hasDataAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getDataAddress() {
      return dataAddress_;
    }
    
    // required string file_name = 4;
    public static final int FILE_NAME_FIELD_NUMBER = 4;
    private Object fileName_;
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getFileName() {
      Object ref = fileName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 alarm_code = 5;
    public static final int ALARM_CODE_FIELD_NUMBER = 5;
    private int alarmCode_;
    public boolean hasAlarmCode() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getAlarmCode() {
      return alarmCode_;
    }
    
    // required float longitude = 6;
    public static final int LONGITUDE_FIELD_NUMBER = 6;
    private float longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public float getLongitude() {
      return longitude_;
    }
    
    // required float latitude = 7;
    public static final int LATITUDE_FIELD_NUMBER = 7;
    private float latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public float getLatitude() {
      return latitude_;
    }
    
    // required string device_name = 8;
    public static final int DEVICE_NAME_FIELD_NUMBER = 8;
    private Object deviceName_;
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getDeviceName() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceNameBytes() {
      Object ref = deviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double longitude_double = 9;
    public static final int LONGITUDE_DOUBLE_FIELD_NUMBER = 9;
    private double longitudeDouble_;
    public boolean hasLongitudeDouble() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public double getLongitudeDouble() {
      return longitudeDouble_;
    }
    
    // required double latitude_double = 10;
    public static final int LATITUDE_DOUBLE_FIELD_NUMBER = 10;
    private double latitudeDouble_;
    public boolean hasLatitudeDouble() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public double getLatitudeDouble() {
      return latitudeDouble_;
    }
    
    // required bytes alarm_code_array = 11;
    public static final int ALARM_CODE_ARRAY_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString alarmCodeArray_;
    public boolean hasAlarmCodeArray() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public com.google.protobuf.ByteString getAlarmCodeArray() {
      return alarmCodeArray_;
    }
    
    private void initFields() {
      uid_ = "";
      modAddress_ = com.google.protobuf.ByteString.EMPTY;
      dataAddress_ = com.google.protobuf.ByteString.EMPTY;
      fileName_ = "";
      alarmCode_ = 0;
      longitude_ = 0F;
      latitude_ = 0F;
      deviceName_ = "";
      longitudeDouble_ = 0D;
      latitudeDouble_ = 0D;
      alarmCodeArray_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitudeDouble()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitudeDouble()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmCodeArray()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, modAddress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, dataAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, alarmCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, longitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, latitude_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, longitudeDouble_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(10, latitudeDouble_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, alarmCodeArray_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, modAddress_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, dataAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, alarmCode_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, longitude_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, latitude_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, longitudeDouble_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, latitudeDouble_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, alarmCodeArray_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static single_online_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static single_online_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static single_online_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static single_online_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static single_online_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static single_online_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static single_online_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static single_online_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static single_online_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static single_online_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(single_online_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements single_online_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return online_info.internal_static_com_ideal_logic_single_online_info_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return online_info.internal_static_com_ideal_logic_single_online_info_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.online_info.single_online_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        modAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        dataAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        alarmCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        longitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        latitude_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        longitudeDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        latitudeDouble_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        alarmCodeArray_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return single_online_info.getDescriptor();
      }
      
      public single_online_info getDefaultInstanceForType() {
        return single_online_info.getDefaultInstance();
      }
      
      public single_online_info build() {
        single_online_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private single_online_info buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        single_online_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public single_online_info buildPartial() {
        single_online_info result = new single_online_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.modAddress_ = modAddress_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataAddress_ = dataAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.alarmCode_ = alarmCode_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.longitudeDouble_ = longitudeDouble_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.latitudeDouble_ = latitudeDouble_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.alarmCodeArray_ = alarmCodeArray_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof single_online_info) {
          return mergeFrom((single_online_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(single_online_info other) {
        if (other == single_online_info.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasModAddress()) {
          setModAddress(other.getModAddress());
        }
        if (other.hasDataAddress()) {
          setDataAddress(other.getDataAddress());
        }
        if (other.hasFileName()) {
          setFileName(other.getFileName());
        }
        if (other.hasAlarmCode()) {
          setAlarmCode(other.getAlarmCode());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasDeviceName()) {
          setDeviceName(other.getDeviceName());
        }
        if (other.hasLongitudeDouble()) {
          setLongitudeDouble(other.getLongitudeDouble());
        }
        if (other.hasLatitudeDouble()) {
          setLatitudeDouble(other.getLatitudeDouble());
        }
        if (other.hasAlarmCodeArray()) {
          setAlarmCodeArray(other.getAlarmCodeArray());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasModAddress()) {
          
          return false;
        }
        if (!hasDataAddress()) {
          
          return false;
        }
        if (!hasFileName()) {
          
          return false;
        }
        if (!hasAlarmCode()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasDeviceName()) {
          
          return false;
        }
        if (!hasLongitudeDouble()) {
          
          return false;
        }
        if (!hasLatitudeDouble()) {
          
          return false;
        }
        if (!hasAlarmCodeArray()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              modAddress_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dataAddress_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fileName_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              alarmCode_ = input.readInt32();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              longitude_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              latitude_ = input.readFloat();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              deviceName_ = input.readBytes();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              longitudeDouble_ = input.readDouble();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              latitudeDouble_ = input.readDouble();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              alarmCodeArray_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uid = 1;
      private Object uid_ = "";
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUid() {
        Object ref = uid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      void setUid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
      }
      
      // required bytes mod_address = 2;
      private com.google.protobuf.ByteString modAddress_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasModAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getModAddress() {
        return modAddress_;
      }
      public Builder setModAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        modAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearModAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        modAddress_ = getDefaultInstance().getModAddress();
        onChanged();
        return this;
      }
      
      // required bytes data_address = 3;
      private com.google.protobuf.ByteString dataAddress_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasDataAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getDataAddress() {
        return dataAddress_;
      }
      public Builder setDataAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataAddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataAddress_ = getDefaultInstance().getDataAddress();
        onChanged();
        return this;
      }
      
      // required string file_name = 4;
      private Object fileName_ = "";
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getFileName() {
        Object ref = fileName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fileName_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      void setFileName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        fileName_ = value;
        onChanged();
      }
      
      // required int32 alarm_code = 5;
      private int alarmCode_ ;
      public boolean hasAlarmCode() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getAlarmCode() {
        return alarmCode_;
      }
      public Builder setAlarmCode(int value) {
        bitField0_ |= 0x00000010;
        alarmCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlarmCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        alarmCode_ = 0;
        onChanged();
        return this;
      }
      
      // required float longitude = 6;
      private float longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public float getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(float value) {
        bitField0_ |= 0x00000020;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000020);
        longitude_ = 0F;
        onChanged();
        return this;
      }
      
      // required float latitude = 7;
      private float latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public float getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(float value) {
        bitField0_ |= 0x00000040;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000040);
        latitude_ = 0F;
        onChanged();
        return this;
      }
      
      // required string device_name = 8;
      private Object deviceName_ = "";
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getDeviceName() {
        Object ref = deviceName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        deviceName_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000080);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      void setDeviceName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        deviceName_ = value;
        onChanged();
      }
      
      // required double longitude_double = 9;
      private double longitudeDouble_ ;
      public boolean hasLongitudeDouble() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public double getLongitudeDouble() {
        return longitudeDouble_;
      }
      public Builder setLongitudeDouble(double value) {
        bitField0_ |= 0x00000100;
        longitudeDouble_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitudeDouble() {
        bitField0_ = (bitField0_ & ~0x00000100);
        longitudeDouble_ = 0D;
        onChanged();
        return this;
      }
      
      // required double latitude_double = 10;
      private double latitudeDouble_ ;
      public boolean hasLatitudeDouble() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public double getLatitudeDouble() {
        return latitudeDouble_;
      }
      public Builder setLatitudeDouble(double value) {
        bitField0_ |= 0x00000200;
        latitudeDouble_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitudeDouble() {
        bitField0_ = (bitField0_ & ~0x00000200);
        latitudeDouble_ = 0D;
        onChanged();
        return this;
      }
      
      // required bytes alarm_code_array = 11;
      private com.google.protobuf.ByteString alarmCodeArray_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAlarmCodeArray() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public com.google.protobuf.ByteString getAlarmCodeArray() {
        return alarmCodeArray_;
      }
      public Builder setAlarmCodeArray(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        alarmCodeArray_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlarmCodeArray() {
        bitField0_ = (bitField0_ & ~0x00000400);
        alarmCodeArray_ = getDefaultInstance().getAlarmCodeArray();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.single_online_info)
    }
    
    static {
      defaultInstance = new single_online_info(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.single_online_info)
  }
  
  public interface update_online_status_resultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
    
    // repeated .com.ideal.logic.single_online_info info = 2;
    java.util.List<single_online_info>
        getInfoList();
    single_online_info getInfo(int index);
    int getInfoCount();
    java.util.List<? extends single_online_infoOrBuilder>
        getInfoOrBuilderList();
    single_online_infoOrBuilder getInfoOrBuilder(
            int index);
  }
  public static final class update_online_status_result extends
      com.google.protobuf.GeneratedMessage
      implements update_online_status_resultOrBuilder {
    // Use update_online_status_result.newBuilder() to construct.
    private update_online_status_result(Builder builder) {
      super(builder);
    }
    private update_online_status_result(boolean noInit) {}
    
    private static final update_online_status_result defaultInstance;
    public static update_online_status_result getDefaultInstance() {
      return defaultInstance;
    }
    
    public update_online_status_result getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return online_info.internal_static_com_ideal_logic_update_online_status_result_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return online_info.internal_static_com_ideal_logic_update_online_status_result_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    // repeated .com.ideal.logic.single_online_info info = 2;
    public static final int INFO_FIELD_NUMBER = 2;
    private java.util.List<single_online_info> info_;
    public java.util.List<single_online_info> getInfoList() {
      return info_;
    }
    public java.util.List<? extends single_online_infoOrBuilder>
        getInfoOrBuilderList() {
      return info_;
    }
    public int getInfoCount() {
      return info_.size();
    }
    public single_online_info getInfo(int index) {
      return info_.get(index);
    }
    public single_online_infoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }
    
    private void initFields() {
      result_ = 0;
      info_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInfoCount(); i++) {
        if (!getInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(2, info_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, info_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static update_online_status_result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static update_online_status_result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static update_online_status_result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static update_online_status_result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static update_online_status_result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static update_online_status_result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static update_online_status_result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static update_online_status_result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static update_online_status_result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static update_online_status_result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(update_online_status_result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements update_online_status_resultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return online_info.internal_static_com_ideal_logic_update_online_status_result_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return online_info.internal_static_com_ideal_logic_update_online_status_result_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.online_info.update_online_status_result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return update_online_status_result.getDescriptor();
      }
      
      public update_online_status_result getDefaultInstanceForType() {
        return update_online_status_result.getDefaultInstance();
      }
      
      public update_online_status_result build() {
        update_online_status_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private update_online_status_result buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        update_online_status_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public update_online_status_result buildPartial() {
        update_online_status_result result = new update_online_status_result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof update_online_status_result) {
          return mergeFrom((update_online_status_result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(update_online_status_result other) {
        if (other == update_online_status_result.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000002);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        for (int i = 0; i < getInfoCount(); i++) {
          if (!getInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              single_online_info.Builder subBuilder = single_online_info.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.ideal.logic.single_online_info info = 2;
      private java.util.List<single_online_info> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          info_ = new java.util.ArrayList<single_online_info>(info_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          single_online_info, single_online_info.Builder, single_online_infoOrBuilder> infoBuilder_;
      
      public java.util.List<single_online_info> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      public single_online_info getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      public Builder setInfo(
          int index, single_online_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setInfo(
          int index, single_online_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addInfo(single_online_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addInfo(
          int index, single_online_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addInfo(
          single_online_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addInfo(
          int index, single_online_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllInfo(
          Iterable<? extends single_online_info> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          super.addAll(values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      public single_online_info.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      public single_online_infoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends single_online_infoOrBuilder>
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      public single_online_info.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            single_online_info.getDefaultInstance());
      }
      public single_online_info.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, single_online_info.getDefaultInstance());
      }
      public java.util.List<single_online_info.Builder>
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          single_online_info, single_online_info.Builder, single_online_infoOrBuilder>
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              single_online_info, single_online_info.Builder, single_online_infoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.update_online_status_result)
    }
    
    static {
      defaultInstance = new update_online_status_result(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.update_online_status_result)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_update_online_status_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_update_online_status_request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_single_online_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_single_online_info_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_update_online_status_result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_update_online_status_result_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027logic/online_info.proto\022\017com.ideal.log" +
      "ic\"1\n\034update_online_status_request\022\021\n\tus" +
      "er_name\030\001 \002(\t\"\372\001\n\022single_online_info\022\013\n\003" +
      "uid\030\001 \002(\t\022\023\n\013mod_address\030\002 \002(\014\022\024\n\014data_a" +
      "ddress\030\003 \002(\014\022\021\n\tfile_name\030\004 \002(\t\022\022\n\nalarm" +
      "_code\030\005 \002(\005\022\021\n\tlongitude\030\006 \002(\002\022\020\n\010latitu" +
      "de\030\007 \002(\002\022\023\n\013device_name\030\010 \002(\t\022\030\n\020longitu" +
      "de_double\030\t \002(\001\022\027\n\017latitude_double\030\n \002(\001" +
      "\022\030\n\020alarm_code_array\030\013 \002(\014\"`\n\033update_onl" +
      "ine_status_result\022\016\n\006result\030\001 \002(\005\0221\n\004inf",
      "o\030\002 \003(\0132#.com.ideal.logic.single_online_" +
      "infoB$\n\017com.ideal.logicB\013online_info\200\001\001\210" +
      "\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ideal_logic_update_online_status_request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ideal_logic_update_online_status_request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_update_online_status_request_descriptor,
              new String[] { "UserName", },
              update_online_status_request.class,
              update_online_status_request.Builder.class);
          internal_static_com_ideal_logic_single_online_info_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ideal_logic_single_online_info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_single_online_info_descriptor,
              new String[] { "Uid", "ModAddress", "DataAddress", "FileName", "AlarmCode", "Longitude", "Latitude", "DeviceName", "LongitudeDouble", "LatitudeDouble", "AlarmCodeArray", },
              single_online_info.class,
              single_online_info.Builder.class);
          internal_static_com_ideal_logic_update_online_status_result_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_ideal_logic_update_online_status_result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_update_online_status_result_descriptor,
              new String[] { "Result", "Info", },
              update_online_status_result.class,
              update_online_status_result.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
