// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logic/server_lastestdata.proto

package com.ideal.logic;

public final class server_lastestdata {
  private server_lastestdata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface reg_server_lastestdataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string uuid = 1;
    boolean hasUuid();
    String getUuid();
    
    // optional string company = 2;
    boolean hasCompany();
    String getCompany();
  }
  public static final class reg_server_lastestdata extends
      com.google.protobuf.GeneratedMessage
      implements reg_server_lastestdataOrBuilder {
    // Use reg_server_lastestdata.newBuilder() to construct.
    private reg_server_lastestdata(Builder builder) {
      super(builder);
    }
    private reg_server_lastestdata(boolean noInit) {}
    
    private static final reg_server_lastestdata defaultInstance;
    public static reg_server_lastestdata getDefaultInstance() {
      return defaultInstance;
    }
    
    public reg_server_lastestdata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server_lastestdata.internal_static_com_ideal_logic_reg_server_lastestdata_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server_lastestdata.internal_static_com_ideal_logic_reg_server_lastestdata_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string uuid = 1;
    public static final int UUID_FIELD_NUMBER = 1;
    private Object uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string company = 2;
    public static final int COMPANY_FIELD_NUMBER = 2;
    private Object company_;
    public boolean hasCompany() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCompany() {
      Object ref = company_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          company_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCompanyBytes() {
      Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uuid_ = "";
      company_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCompanyBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCompanyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static reg_server_lastestdata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static reg_server_lastestdata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static reg_server_lastestdata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static reg_server_lastestdata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static reg_server_lastestdata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static reg_server_lastestdata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static reg_server_lastestdata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static reg_server_lastestdata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static reg_server_lastestdata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static reg_server_lastestdata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(reg_server_lastestdata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements reg_server_lastestdataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server_lastestdata.internal_static_com_ideal_logic_reg_server_lastestdata_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server_lastestdata.internal_static_com_ideal_logic_reg_server_lastestdata_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.server_lastestdata.reg_server_lastestdata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        company_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return reg_server_lastestdata.getDescriptor();
      }
      
      public reg_server_lastestdata getDefaultInstanceForType() {
        return reg_server_lastestdata.getDefaultInstance();
      }
      
      public reg_server_lastestdata build() {
        reg_server_lastestdata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private reg_server_lastestdata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        reg_server_lastestdata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public reg_server_lastestdata buildPartial() {
        reg_server_lastestdata result = new reg_server_lastestdata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.company_ = company_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof reg_server_lastestdata) {
          return mergeFrom((reg_server_lastestdata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(reg_server_lastestdata other) {
        if (other == reg_server_lastestdata.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasCompany()) {
          setCompany(other.getCompany());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUuid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              company_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uuid = 1;
      private Object uuid_ = "";
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      void setUuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
      }
      
      // optional string company = 2;
      private Object company_ = "";
      public boolean hasCompany() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCompany() {
        Object ref = company_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCompany(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        company_ = value;
        onChanged();
        return this;
      }
      public Builder clearCompany() {
        bitField0_ = (bitField0_ & ~0x00000002);
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      void setCompany(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        company_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.reg_server_lastestdata)
    }
    
    static {
      defaultInstance = new reg_server_lastestdata(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.reg_server_lastestdata)
  }
  
  public interface server_lastestdata_responseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
    
    // repeated .com.ideal.logic.lastestdata_info info = 2;
    java.util.List<lastestdata_info>
        getInfoList();
    lastestdata_info getInfo(int index);
    int getInfoCount();
    java.util.List<? extends lastestdata_infoOrBuilder>
        getInfoOrBuilderList();
    lastestdata_infoOrBuilder getInfoOrBuilder(
            int index);
  }
  public static final class server_lastestdata_response extends
      com.google.protobuf.GeneratedMessage
      implements server_lastestdata_responseOrBuilder {
    // Use server_lastestdata_response.newBuilder() to construct.
    private server_lastestdata_response(Builder builder) {
      super(builder);
    }
    private server_lastestdata_response(boolean noInit) {}
    
    private static final server_lastestdata_response defaultInstance;
    public static server_lastestdata_response getDefaultInstance() {
      return defaultInstance;
    }
    
    public server_lastestdata_response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server_lastestdata.internal_static_com_ideal_logic_server_lastestdata_response_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server_lastestdata.internal_static_com_ideal_logic_server_lastestdata_response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    // repeated .com.ideal.logic.lastestdata_info info = 2;
    public static final int INFO_FIELD_NUMBER = 2;
    private java.util.List<lastestdata_info> info_;
    public java.util.List<lastestdata_info> getInfoList() {
      return info_;
    }
    public java.util.List<? extends lastestdata_infoOrBuilder>
        getInfoOrBuilderList() {
      return info_;
    }
    public int getInfoCount() {
      return info_.size();
    }
    public lastestdata_info getInfo(int index) {
      return info_.get(index);
    }
    public lastestdata_infoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }
    
    private void initFields() {
      result_ = 0;
      info_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInfoCount(); i++) {
        if (!getInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(2, info_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, info_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static server_lastestdata_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static server_lastestdata_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static server_lastestdata_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static server_lastestdata_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static server_lastestdata_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static server_lastestdata_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static server_lastestdata_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static server_lastestdata_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static server_lastestdata_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static server_lastestdata_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(server_lastestdata_response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements server_lastestdata_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server_lastestdata.internal_static_com_ideal_logic_server_lastestdata_response_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server_lastestdata.internal_static_com_ideal_logic_server_lastestdata_response_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.server_lastestdata.server_lastestdata_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return server_lastestdata_response.getDescriptor();
      }
      
      public server_lastestdata_response getDefaultInstanceForType() {
        return server_lastestdata_response.getDefaultInstance();
      }
      
      public server_lastestdata_response build() {
        server_lastestdata_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private server_lastestdata_response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        server_lastestdata_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public server_lastestdata_response buildPartial() {
        server_lastestdata_response result = new server_lastestdata_response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof server_lastestdata_response) {
          return mergeFrom((server_lastestdata_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(server_lastestdata_response other) {
        if (other == server_lastestdata_response.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000002);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        for (int i = 0; i < getInfoCount(); i++) {
          if (!getInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
            case 18: {
              lastestdata_info.Builder subBuilder = lastestdata_info.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.ideal.logic.lastestdata_info info = 2;
      private java.util.List<lastestdata_info> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          info_ = new java.util.ArrayList<lastestdata_info>(info_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          lastestdata_info, lastestdata_info.Builder, lastestdata_infoOrBuilder> infoBuilder_;
      
      public java.util.List<lastestdata_info> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      public lastestdata_info getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      public Builder setInfo(
          int index, lastestdata_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setInfo(
          int index, lastestdata_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addInfo(lastestdata_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addInfo(
          int index, lastestdata_info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addInfo(
          lastestdata_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addInfo(
          int index, lastestdata_info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllInfo(
          Iterable<? extends lastestdata_info> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          super.addAll(values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      public lastestdata_info.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      public lastestdata_infoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends lastestdata_infoOrBuilder>
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      public lastestdata_info.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            lastestdata_info.getDefaultInstance());
      }
      public lastestdata_info.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, lastestdata_info.getDefaultInstance());
      }
      public java.util.List<lastestdata_info.Builder>
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          lastestdata_info, lastestdata_info.Builder, lastestdata_infoOrBuilder>
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              lastestdata_info, lastestdata_info.Builder, lastestdata_infoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.server_lastestdata_response)
    }
    
    static {
      defaultInstance = new server_lastestdata_response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.server_lastestdata_response)
  }
  
  public interface lastestdata_infoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes info = 1;
    boolean hasInfo();
    com.google.protobuf.ByteString getInfo();
    
    // required uint64 time = 2;
    boolean hasTime();
    long getTime();
    
    // required bytes modbus_msg = 3;
    boolean hasModbusMsg();
    com.google.protobuf.ByteString getModbusMsg();
    
    // required bytes alarmcode = 4;
    boolean hasAlarmcode();
    com.google.protobuf.ByteString getAlarmcode();
  }
  public static final class lastestdata_info extends
      com.google.protobuf.GeneratedMessage
      implements lastestdata_infoOrBuilder {
    // Use lastestdata_info.newBuilder() to construct.
    private lastestdata_info(Builder builder) {
      super(builder);
    }
    private lastestdata_info(boolean noInit) {}
    
    private static final lastestdata_info defaultInstance;
    public static lastestdata_info getDefaultInstance() {
      return defaultInstance;
    }
    
    public lastestdata_info getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server_lastestdata.internal_static_com_ideal_logic_lastestdata_info_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server_lastestdata.internal_static_com_ideal_logic_lastestdata_info_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getInfo() {
      return info_;
    }
    
    // required uint64 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTime() {
      return time_;
    }
    
    // required bytes modbus_msg = 3;
    public static final int MODBUS_MSG_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString modbusMsg_;
    public boolean hasModbusMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getModbusMsg() {
      return modbusMsg_;
    }
    
    // required bytes alarmcode = 4;
    public static final int ALARMCODE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString alarmcode_;
    public boolean hasAlarmcode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getAlarmcode() {
      return alarmcode_;
    }
    
    private void initFields() {
      info_ = com.google.protobuf.ByteString.EMPTY;
      time_ = 0L;
      modbusMsg_ = com.google.protobuf.ByteString.EMPTY;
      alarmcode_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasModbusMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAlarmcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, modbusMsg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, alarmcode_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, info_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, modbusMsg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, alarmcode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static lastestdata_info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lastestdata_info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lastestdata_info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lastestdata_info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lastestdata_info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lastestdata_info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static lastestdata_info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lastestdata_info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lastestdata_info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lastestdata_info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lastestdata_info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lastestdata_infoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server_lastestdata.internal_static_com_ideal_logic_lastestdata_info_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server_lastestdata.internal_static_com_ideal_logic_lastestdata_info_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.server_lastestdata.lastestdata_info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        info_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        modbusMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        alarmcode_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lastestdata_info.getDescriptor();
      }
      
      public lastestdata_info getDefaultInstanceForType() {
        return lastestdata_info.getDefaultInstance();
      }
      
      public lastestdata_info build() {
        lastestdata_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private lastestdata_info buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        lastestdata_info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public lastestdata_info buildPartial() {
        lastestdata_info result = new lastestdata_info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.modbusMsg_ = modbusMsg_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.alarmcode_ = alarmcode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lastestdata_info) {
          return mergeFrom((lastestdata_info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(lastestdata_info other) {
        if (other == lastestdata_info.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          setInfo(other.getInfo());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasModbusMsg()) {
          setModbusMsg(other.getModbusMsg());
        }
        if (other.hasAlarmcode()) {
          setAlarmcode(other.getAlarmcode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        if (!hasModbusMsg()) {
          
          return false;
        }
        if (!hasAlarmcode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              info_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              modbusMsg_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              alarmcode_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes info = 1;
      private com.google.protobuf.ByteString info_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getInfo() {
        return info_;
      }
      public Builder setInfo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        info_ = value;
        onChanged();
        return this;
      }
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      
      // required uint64 time = 2;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        onChanged();
        return this;
      }
      
      // required bytes modbus_msg = 3;
      private com.google.protobuf.ByteString modbusMsg_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasModbusMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getModbusMsg() {
        return modbusMsg_;
      }
      public Builder setModbusMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        modbusMsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearModbusMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        modbusMsg_ = getDefaultInstance().getModbusMsg();
        onChanged();
        return this;
      }
      
      // required bytes alarmcode = 4;
      private com.google.protobuf.ByteString alarmcode_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAlarmcode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getAlarmcode() {
        return alarmcode_;
      }
      public Builder setAlarmcode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        alarmcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearAlarmcode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        alarmcode_ = getDefaultInstance().getAlarmcode();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.lastestdata_info)
    }
    
    static {
      defaultInstance = new lastestdata_info(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.lastestdata_info)
  }
  
  public interface unreg_server_lastestdataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string uuid = 1;
    boolean hasUuid();
    String getUuid();
  }
  public static final class unreg_server_lastestdata extends
      com.google.protobuf.GeneratedMessage
      implements unreg_server_lastestdataOrBuilder {
    // Use unreg_server_lastestdata.newBuilder() to construct.
    private unreg_server_lastestdata(Builder builder) {
      super(builder);
    }
    private unreg_server_lastestdata(boolean noInit) {}
    
    private static final unreg_server_lastestdata defaultInstance;
    public static unreg_server_lastestdata getDefaultInstance() {
      return defaultInstance;
    }
    
    public unreg_server_lastestdata getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server_lastestdata.internal_static_com_ideal_logic_unreg_server_lastestdata_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server_lastestdata.internal_static_com_ideal_logic_unreg_server_lastestdata_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string uuid = 1;
    public static final int UUID_FIELD_NUMBER = 1;
    private Object uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uuid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUuidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static unreg_server_lastestdata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static unreg_server_lastestdata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static unreg_server_lastestdata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static unreg_server_lastestdata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static unreg_server_lastestdata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static unreg_server_lastestdata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static unreg_server_lastestdata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static unreg_server_lastestdata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static unreg_server_lastestdata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static unreg_server_lastestdata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(unreg_server_lastestdata prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements unreg_server_lastestdataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server_lastestdata.internal_static_com_ideal_logic_unreg_server_lastestdata_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server_lastestdata.internal_static_com_ideal_logic_unreg_server_lastestdata_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.server_lastestdata.unreg_server_lastestdata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return unreg_server_lastestdata.getDescriptor();
      }
      
      public unreg_server_lastestdata getDefaultInstanceForType() {
        return unreg_server_lastestdata.getDefaultInstance();
      }
      
      public unreg_server_lastestdata build() {
        unreg_server_lastestdata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private unreg_server_lastestdata buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        unreg_server_lastestdata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public unreg_server_lastestdata buildPartial() {
        unreg_server_lastestdata result = new unreg_server_lastestdata(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof unreg_server_lastestdata) {
          return mergeFrom((unreg_server_lastestdata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(unreg_server_lastestdata other) {
        if (other == unreg_server_lastestdata.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUuid()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uuid = 1;
      private Object uuid_ = "";
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      void setUuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.unreg_server_lastestdata)
    }
    
    static {
      defaultInstance = new unreg_server_lastestdata(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.unreg_server_lastestdata)
  }
  
  public interface unreg_lastestdata_responseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 result = 1;
    boolean hasResult();
    int getResult();
  }
  public static final class unreg_lastestdata_response extends
      com.google.protobuf.GeneratedMessage
      implements unreg_lastestdata_responseOrBuilder {
    // Use unreg_lastestdata_response.newBuilder() to construct.
    private unreg_lastestdata_response(Builder builder) {
      super(builder);
    }
    private unreg_lastestdata_response(boolean noInit) {}
    
    private static final unreg_lastestdata_response defaultInstance;
    public static unreg_lastestdata_response getDefaultInstance() {
      return defaultInstance;
    }
    
    public unreg_lastestdata_response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return server_lastestdata.internal_static_com_ideal_logic_unreg_lastestdata_response_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return server_lastestdata.internal_static_com_ideal_logic_unreg_lastestdata_response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getResult() {
      return result_;
    }
    
    private void initFields() {
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, result_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static unreg_lastestdata_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static unreg_lastestdata_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static unreg_lastestdata_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static unreg_lastestdata_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static unreg_lastestdata_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static unreg_lastestdata_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static unreg_lastestdata_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static unreg_lastestdata_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static unreg_lastestdata_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static unreg_lastestdata_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(unreg_lastestdata_response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements unreg_lastestdata_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return server_lastestdata.internal_static_com_ideal_logic_unreg_lastestdata_response_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return server_lastestdata.internal_static_com_ideal_logic_unreg_lastestdata_response_fieldAccessorTable;
      }
      
      // Construct using com.ideal.logic.server_lastestdata.unreg_lastestdata_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return unreg_lastestdata_response.getDescriptor();
      }
      
      public unreg_lastestdata_response getDefaultInstanceForType() {
        return unreg_lastestdata_response.getDefaultInstance();
      }
      
      public unreg_lastestdata_response build() {
        unreg_lastestdata_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private unreg_lastestdata_response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        unreg_lastestdata_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public unreg_lastestdata_response buildPartial() {
        unreg_lastestdata_response result = new unreg_lastestdata_response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof unreg_lastestdata_response) {
          return mergeFrom((unreg_lastestdata_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(unreg_lastestdata_response other) {
        if (other == unreg_lastestdata_response.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 result = 1;
      private int result_ ;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getResult() {
        return result_;
      }
      public Builder setResult(int value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.ideal.logic.unreg_lastestdata_response)
    }
    
    static {
      defaultInstance = new unreg_lastestdata_response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.ideal.logic.unreg_lastestdata_response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_reg_server_lastestdata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_reg_server_lastestdata_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_server_lastestdata_response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_server_lastestdata_response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_lastestdata_info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_lastestdata_info_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_unreg_server_lastestdata_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_unreg_server_lastestdata_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ideal_logic_unreg_lastestdata_response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ideal_logic_unreg_lastestdata_response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036logic/server_lastestdata.proto\022\017com.id" +
      "eal.logic\"7\n\026reg_server_lastestdata\022\014\n\004u" +
      "uid\030\001 \002(\t\022\017\n\007company\030\002 \001(\t\"^\n\033server_las" +
      "testdata_response\022\016\n\006result\030\001 \002(\005\022/\n\004inf" +
      "o\030\002 \003(\0132!.com.ideal.logic.lastestdata_in" +
      "fo\"U\n\020lastestdata_info\022\014\n\004info\030\001 \002(\014\022\014\n\004" +
      "time\030\002 \002(\004\022\022\n\nmodbus_msg\030\003 \002(\014\022\021\n\talarmc" +
      "ode\030\004 \002(\014\"(\n\030unreg_server_lastestdata\022\014\n" +
      "\004uuid\030\001 \002(\t\",\n\032unreg_lastestdata_respons" +
      "e\022\016\n\006result\030\001 \002(\005B+\n\017com.ideal.logicB\022se",
      "rver_lastestdata\200\001\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ideal_logic_reg_server_lastestdata_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ideal_logic_reg_server_lastestdata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_reg_server_lastestdata_descriptor,
              new String[] { "Uuid", "Company", },
              reg_server_lastestdata.class,
              reg_server_lastestdata.Builder.class);
          internal_static_com_ideal_logic_server_lastestdata_response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_ideal_logic_server_lastestdata_response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_server_lastestdata_response_descriptor,
              new String[] { "Result", "Info", },
              server_lastestdata_response.class,
              server_lastestdata_response.Builder.class);
          internal_static_com_ideal_logic_lastestdata_info_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_ideal_logic_lastestdata_info_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_lastestdata_info_descriptor,
              new String[] { "Info", "Time", "ModbusMsg", "Alarmcode", },
              lastestdata_info.class,
              lastestdata_info.Builder.class);
          internal_static_com_ideal_logic_unreg_server_lastestdata_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_ideal_logic_unreg_server_lastestdata_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_unreg_server_lastestdata_descriptor,
              new String[] { "Uuid", },
              unreg_server_lastestdata.class,
              unreg_server_lastestdata.Builder.class);
          internal_static_com_ideal_logic_unreg_lastestdata_response_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_ideal_logic_unreg_lastestdata_response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ideal_logic_unreg_lastestdata_response_descriptor,
              new String[] { "Result", },
              unreg_lastestdata_response.class,
              unreg_lastestdata_response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
